format_version = 1

welcome_message = """
Is this your first time? No worries, Rustgrind is designed to help you
improve at solving LeetCode-style problems while practicing Rust! 
Here's how it works:

1. Rustgrind is centered around the NeetCode 150 problems, carefully curated 
   to strengthen your problem-solving and algorithmic thinking skills, all in Rust.

2. Keep your editor open in the rustgrind/ directory. Rustgrind will display
   the path of the current problem. Open the corresponding file, implement 
   your solution, and save the file. Rustgrind will automatically detect changes,
   run the tests, and provide feedback. If all tests pass, you'll move on to the
   next problem.

3. If you're struggling, type h to see a hint for the current problem.

Rustgrind is your companion to mastering Rust and cracking coding interviews. Ready to grind?"""

final_message = """
We hope you enjoyed learning about the various aspects of Rust!
If you noticed any issues, don't hesitate to report them on Github.
You can also contribute your own exercises to help the greater community!

Before reporting an issue or contributing, please read our guidelines:
https://github.com/0XYoussefX0/rustgrind/blob/main/CONTRIBUTING.md"""

# ARRAYS_AND_HASHING

[[problems]]
name = "01_intro"
dir = "01_Arrays_&_Hashing"
test = false
skip_check_unsolved = true
hints = [
"""
Enter `n` to move on to the next exercise.
You might need to press ENTER after typing `n`."""
]


[[problems]]
name = "02_two_sum"
dir = "01_Arrays_&_Hashing"
test = false
hints = [
    """
    Todo
    """
]

[[problems]]
name = "03_contains_duplicate"
dir = "01_Arrays_&_Hashing"
test = false
hints = [
    """
    Todo
    """
]

[[problems]]
name = "04_valid_anagram"
dir = "01_Arrays_&_Hashing"
test = false
hints = [
    """
    Todo
    """
]